### ISSUE TITLE
kata sample admission controller: Move to kata repository

### ISSUE THREAD

**Issue by mcastelino** [clearlinux/cloud-native-setup#3]
Currently the simple admission controller `mcastelino/kubewebhook-pod-annotate-example:1.0` is based on https://github.com/mcastelino/kubewebhook/tree/topic/hack-kata/examples/pod-annotate.

This needs to be moved to a kata specific repository and hosted under the kata dockerhub.

**Comment by krsna1729** [comment]
Adding a comment here since I am unable to create an issue at the forked repo -

We should coordinate with [kata-deploy](https://github.com/kata-containers/packaging/blob/master/kata-deploy/README.md) labels and add `nodeSelector` field to get scheduled only on nodes with `kata` installed.

We should also add these labels in our [kubeadm.yaml](cloud-native-setup/clr-k8s-examples/kubeadm.yaml) file.

**Comment by krsna1729** [comment]
Actually on second thought, assuming a homogeneous Clear cluster, all nodes would be capable of running kata runtimeClass. So we may not need the labels and nodeSelector. WDYT?

/cc @egernst

**Comment by egernst** [comment]
Personally, I'd like to see this under Kata, as this is very kata + k8s specific, and distro agnostic.

**Comment by krsna1729** [comment]
Resolved-by: https://github.com/kata-containers/tests/pull/1080
